apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP

