apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  selector:
    app: influxdb
  type: LoadBalancer
  ports:
  - port: 8086
    targetPort: 8086
    protocol: TCP
