apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  selector:
    app: mysql
  type: LoadBalancer
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP

